### ISSUE TITLE
config list(查询弹性伸缩配置列表)文档中命令举例有误

### ISSUE THREAD

**Issue by caoyameng** [Huawei/OpenStackClient_Auto-Scaling#1]
文档链接：https://github.com/Huawei/OpenStackClient_Auto-Scaling/blob/master/commands.rst

$ openstack as config list --image=image-WS-Joomla  --name=as-config-TEO  --limit=1

应该是$ openstack as config list

**Comment by IamFive** [comment]
后面是对应的查询参数
