### ISSUE TITLE
创建伸缩策略---type：RECURRECE，缺Triggered at设置，和接口文档不一致

### ISSUE THREAD

**Issue by caoyameng** [Huawei/OpenStackClient_Auto-Scaling#13]
1. 当interval为Weekly是，帮助里面没有提到触发时间（Triggered at）如何设置，接口文档中写道在这个触发时间应该在launch-time里面设，但help中说Schedule launch time(Only Effect when policy-type is SCHEDULED），因不能上传截图，具体请参加见弹性伸缩服务接口参考文档的launch-time的说明部分；

2. 当interval为Monthly是，出现同样问题；

3.当interval为Daily时，Triggered at的设置方法和弹性伸缩服务接口文档也不一致，具体请参加见弹性伸缩服务接口参考文档的launch-time的说明部分和scheduled_policy字段说明。

**Comment by IamFive** [comment]
--help 命令里面都有的
1. Weekly:1,2,3 -> 每周的第一，二，三天
2. Monthly:1,2,3 -> 每月的 1，2，3 号
3. Daily:10:00 每天10点

文档上所有的功能都有实现的。最终用户也不可能对着那个文档来使用，是对阵 help 命令来使用的。
不一样的原因是，文档上的设计不好，我觉得这样设计更合理，就这样处理了。你可以跟张锐讨论下，我觉得现在这样更好。

![image](https://cloud.githubusercontent.com/assets/1578702/23541255/1d95f7e6-0021-11e7-9c0d-08fe747b01dc.png)

**Comment by IamFive** [comment]
Fixed

**Comment by caoyameng** [comment]
确认一下：1.Weekly:1,2,3 -> 每周的第一，二，三天，触发时间：xx:xx
2.Monthly:1,2,3 -> 每月的 1，2，3 号,触发时间：xx:xx
3.3.Daily:10:00 每天10;

这个就是上周微信中讨论的1.2缺触发时间的问题，后来已改了吧？

**Comment by IamFive** [comment]
看最新的例子。已经改掉了。

**Comment by IamFive** [comment]
![image](https://cloud.githubusercontent.com/assets/1578702/23593727/bd0eb532-024d-11e7-83f2-276e6f0c6d15.png)

**Comment by IamFive** [comment]
```
$  openstack as policy create WooTest --action=ADD:1 --group=ac8acbb4-e6ce-4890-a9f2-d8712b3d7385
    --type=SCHEDULED --launch-time=2017-02-19T13:40
Policy xxxxxxx created

$ openstack as policy create WooTest --action=ADD:1 --group=ac8acbb4-e6ce-4890-a9f2-d8712b3d7385
    --type=RECURRENCE --start-time=2017-02-19T14:00 --end-time=2017-02-28T23:00
    --recurrence-type=Daily --launch-time=12:00 --action=SET:1
Policy e0eb7de0-aa5b-435c-8d4c-46867fdf087d created

$ openstack as policy create WooTest --action=ADD:1 --group=ac8acbb4-e6ce-4890-a9f2-d8712b3d7385
    --type=RECURRENCE --start-time=2017-02-19T14:00 --end-time=2017-02-28T23:00
    --recurrence-type=Monthly --recurrence-value=1,10,20 --launch-time=12:00 --action=SET:1
Policy e0eb7de0-aa5b-435c-8d4c-46867fdf087d created
```
