### ISSUE TITLE
创建伸缩配置，缺EIP，用户数据

### ISSUE THREAD

**Issue by caoyameng** [Huawei/OpenStackClient_Auto-Scaling#15]
1. EIP,见接口文档
ip_type 是String IP地址类型。
类型枚举值：
bandwidth 是字典数据结构IP地址带宽参数
2.user_data 
String cloud-init用户数据。
支持注入文本、文本文件或gzip文
件。文件内容需要进行base64格式
编码，最大长度32KB。

**Comment by IamFive** [comment]
@ZhangRui219 这个也需要你那确认下，记得老早前跟你说过。

**Comment by IamFive** [comment]
duplicated with issue #16
