### ISSUE TITLE
需要增加内容

### ISSUE THREAD

**Issue by caoyameng** [Huawei/OpenStackClient_Auto-Scaling#16]
1.创建伸缩配置：
增加EIP；
增加USERDATA

2.查询弹性伸缩配置详情：
注入文件 和 用户数据 这两项，实现不知道困难不？如果可以实现的话，建议加上

3.创建弹性伸缩组
AZ: available_zones 。这个我还没找到《地区和终端节
点》这个文档，正在找。
编辑弹性伸缩组，同步修改

**Comment by IamFive** [comment]
1. issue #15 ，EIP 下面有很多参数，userdata 数据格式 需要张锐那边确认
2. 现在没有数据，不知道要怎么处理
3. 等张锐确认了再说吧

**Comment by caoyameng** [comment]
1. 创建伸缩配置，EIP，没有接口查询ip_type和bandwidth（vpc服务没有提供接口），只能根据接口文档传值，与局点强相关——如果不支持不会影响AS正常功能
2.创建伸缩配置，user_data是cloud-init用户数据，开启cloudinit后会支持，后续各局点应该均会支持cloudinit特性
3. 创建伸缩组，available_zones，没有接口查询获取，只能根据接口文档传值，与局点强相关

**Comment by caoyameng** [comment]
user_data ：
String cloud-init
用户数据。支持注入文本、文本文件或gzip文
件。文件内容需要进行base64格式编码，最大长度32KB

**Comment by caoyameng** [comment]
AZ: 
“available_zones‘:["eu-de-01"],

**Comment by caoyameng** [comment]
ip_type——5_bgp，5_lxbgp，5_telcom，5_union等，需要确认
share_type——PER
charging_mode——bandwidth，traffic

available_zones——eu-de-01，eu-de-02，cn-north-1等，需要确认

**Comment by caoyameng** [comment]
目前的处理方法是，把不同局点支持的值都给提供了:
ip_type——5_bgp，5_lxbgp，5_telcom，5_union等，需要确认
share_type——PER
charging_mode——bandwidth，traffic

available_zones——eu-de-01，eu-de-02，cn-north-1等，需要确认

**Comment by caoyameng** [comment]
User_data：对于接口，都是文件流

ip_type——5_bgp,5_telcom,5_union,5_lxbgp,5_dt 
share_type——PER
charging_mode——bandwidth，traffic
available_zones——eu-de-01，eu-de-02，cn-north-1等，不同局点包括现网和类生产可能都不一样，需要确认，很难枚举

**Comment by caoyameng** [comment]
接口文档：
user_data 
否

String cloud-init

用户数据。
支持注入文本、文本文件或gzip文
件。文件内容需要进行base64格式
编码，最大长度32KB。
