### ISSUE TITLE
查询弹性伸缩配置列表，列表没有显示完

### ISSUE THREAD

**Issue by caoyameng** [Huawei/OpenStackClient_Auto-Scaling#6]
我在DT环境看有4页的配置信息列表，但用config list命令返回结果总共显示了两页的配置列表，后面几页的配置列表没有显示。

**Comment by IamFive** [comment]
把具体的debug信息发上来。按理是不可能出现这种情况的。

客户端只管服务器端返回撒，就输出撒。

**Comment by caoyameng** [comment]
不是问题，没有加limit的原因，加上就可以按照要求显示了
