### ISSUE TITLE
group create(创建弹性伸缩组) 缺AZ配置项，缺Notification Mode

### ISSUE THREAD

**Issue by caoyameng** [Huawei/OpenStackClient_Auto-Scaling#7]
group create 和group edit这两个命令问题一样，都是缺AZ配置项，缺Notification Mode。

**Comment by IamFive** [comment]
![image](https://cloud.githubusercontent.com/assets/1578702/23451574/6fa08484-fe9b-11e6-86a6-0094130467e6.png)

涉及到图中这些问题，都先找张锐确认。
